version: '3.3'

services:
  django_graphql_base:
    build:
      context: .
      dockerfile: Dockerfile_base
    image: django_graphql_base
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_graphql_web
    command: python3 /opt/django_graphql/django_graphql/manage.py runserver 0.0.0.0:8000
    container_name: django_graphql_web
    volumes:
      - .:/opt/django_graphql
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - django_graphql_base
  db:
    image: postgres:12.2-alpine
    container_name: django_graphql_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
    depends_on:
      - django_graphql_base
volumes:
  postgres_data:
